config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/test' => 'pages#test'

  get '/seller_signup' => 'sellers#new'
  post '/sellers' => 'sellers#create'

  get '/buyer_signup' => 'buyers#new'
  post '/buyers' => 'buyers#create'

  get '/login' =>   'sessions#new'
  post '/login' =>   'sessions#create_seller'
  post '/login' =>   'sessions#create_buyer'
  get '/logout' => 'sessions#destroy'

  get '/directions' => 'directions#index'

  resources :buyers

  resources :sellers do
    resources :listings, only: [:index, :new, :create]
  end
  resources :listings, only: [:show, :edit, :update, :destroy]

  get '/listings' => 'listings#all_listings'


  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'sessions#destroy'
  #
  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :seller

  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def full_street_address
    "#{self.address} #{self.city}, #{self.state}, #{self.zip}"
  end

  def lat
    self.latitude
  end

  def lng
    self.longitude
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :set_seller, only: [:all_listings, :show, :edit, :update, :destroy]

  def all_listings
    @listings = Listing.all.order("created_at DESC")
  end


  # GET /listings
  # GET /listings.json
  def index
    @seller = Seller.find(params[:seller_id])
    # @buyer = current_buyer
    @listings = @seller.listings
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    # @seller = Seller.find(params[:seller_id])
    @listings = Listing.find(params[:id])
  end

  # GET /listings/new
  def new
    @seller = current_seller
    @listing = @seller.listings.build
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    # @seller = current_seller
    @listing = current_seller.listings.build(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to current_seller, notice: 'Listing was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_seller
      @seller = current_seller
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:description, :latitude, :longitude, :address, :city, :state, :zip, :seller_id)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="text-center">

<%= form_with(model: [ @seller, @seller.listings.build ]) do |form| %>

  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@listing.errors.count, "error") %> prohibited this @listing from being saved:</h5>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
      <%= form.hidden_field :seller_id, id: :seller_id, value: @seller.id %>
  </div>


  <!-- <div>
    <%= "Seller ID" %>
    <br>
    <%= current_seller.id %>
    <br>
    <% form.label :seller_id %>
    <% form.text_area :seller_id, id: :current_seller_id %>
  </div> -->

  <div class="container">
  <hr>
  </div>
  <br>
  <h5> <strong>Address:</strong> </h5>

  <div class="field">
    <%= form.label :address, class: "hidden" %>
    <%= form.text_field :address, placeholder: 'Address' %>

    <%= form.label :city, class: "hidden"  %>
    <%= form.text_field :city, placeholder: 'City' %>

    <%= form.label :state, class: "hidden"  %>
    <%= form.text_field :state, placeholder: 'State' %>

    <%= form.label :zip, class: "hidden"  %>
    <%= form.number_field :zip, placeholder: 'ZIP' %>
  </div>

  <div class="container">
  <hr>
  </div>


<strong >(Optional)</strong>
<br>
<br>
  <div class="field">
    <h5> <strong>Latitude:</strong> </h5>
    <%= form.label :latitude, class:"hidden" %>
    <%= form.text_field :latitude, placeholder: '40.673180' %>
  </div>

  <div class="field">
    <h5> <strong>Longitude:</strong> </h5>
    <%= form.label :longitude, class:"hidden" %>
    <%= form.text_field :longitude, placeholder: '73.972878' %>
  </div>

  <div class="container">
  <hr>
  </div>

  <div class="field">
    <h5> <strong>Description:</strong> </h5>
    <%= form.label :description, class:"hidden" %>
    <br>
    <%= form.text_area :description %>
  </div>

  <div class="container">
  <hr>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

</div>

app/views/listings/all_listings.html.erb
<div class="text-center">

  <div class="card">
<br>
    <p class="display-4"> All Listings </p>
    <hr>

    <div class="container">

      <hr>

      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#exampleModal">
        View All Listings
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel"> All Listings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p class="display-4"> All Listings </p>
<hr>
              <% @listings.each do |listing| %>

                <h3><%= link_to "#{listing.address}", listing %> </h3>
                  listed by <%= link_to "#{listing.seller.email}", @seller %>
              <% end %>
              <br>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      <hr>
      <br>

      <div id="map"></div>

      <br>

      <script>
            function initMap() {

              var lat = 38.812016;
              var lng = -97.504928 ;

              var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 3.5,
                center: {lat, lng}
              });

              // Create an array of alphabetical characters used to label the markers.
              var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

              // Add some markers to the map.
              // Note: The code uses the JavaScript Array.prototype.map() method to
              // create an array of markers based on a given "locations" array.
              // The map() method here has nothing to do with the Google Maps API.
              var markers = locations.map(function(location, i) {
                return new google.maps.Marker({
                  position: location,
                  label: labels[i % labels.length]
                });
              });

              // Add a marker clusterer to manage the markers.
              var markerCluster = new MarkerClusterer(map, markers,
                  {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
            }


            // <% @listings.each do |location| %>
            //
            //   var lat = <%= location.lat %>;
            //   var lng = <%= location.lng %>;
            //
            // var locations = [
            //
            //
            //   {lat, lng},
            //   {lat, lng},
            //   {lat, lng},
            //
            // ]
            //
            // <% end %>
            //

            var locations = []

            <% @listings.each do |location| %>

              var lat = <%= location.lat %>;
              var lng = <%= location.lng %>;

              locations.push({"lat":lat,"lng":lng})

            <% end %>

      </script>

      <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
      </script>

      <script async defer
      src="https://maps.googleapis.com/maps/api/js?&key=AIzaSyCb7XJAeWDd5AXTQpyjeYIU93Gc7CfUpVk&callback=initMap">
      </script>

      <div class="text-center">
      <%= link_to 'Back', :back, class:"btn btn-primary" %>
      </div>
      <br>



    </div>
  </div>
</div>

app/views/listings/edit.html.erb
<div class="text-center">
  <div class="card">
<br>
  <p class="display-4"> Edit Listing</p>


  <div>
<hr>
  <%= link_to 'Delete', @listing, :method => :delete, data:{confirm: "Are you sure you would like to delete this listing forever?"}, class:"btn btn-lg btn-danger" %>

<hr>
</div>



  <%= form_with(model: @listing, local: true) do |form| %>

  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@listing.errors.count, "error") %> prohibited this @listing from being saved:</h5>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
      <%= form.hidden_field :seller_id, id: :seller_id, value: @seller.id %>
  </div>


  <!-- <div>
    <%= "Seller ID" %>
    <br>
    <%= current_seller.id %>
    <br>
    <% form.label :seller_id %>
    <% form.text_area :seller_id, id: :current_seller_id %>
  </div> -->
  <h5> <strong>Address:</strong> </h5>

  <div class="field">
    <%= form.label :address, class: "hidden" %>
    <%= form.text_field :address, placeholder: 'Address' %>

    <%= form.label :city, class: "hidden"  %>
    <%= form.text_field :city, placeholder: 'City' %>

    <%= form.label :state, class: "hidden"  %>
    <%= form.text_field :state, placeholder: 'State' %>

    <%= form.label :zip, class: "hidden"  %>
    <%= form.number_field :zip, placeholder: 'ZIP' %>
  </div>

  <div class="container">
  <hr>
  </div>


<strong >(Completely Optional)</strong>
<br>
<br>
  <div class="field">
    <h5> <strong>Latitude:</strong> </h5>
    <%= form.label :latitude, class:"hidden" %>
    <%= form.text_field :latitude, placeholder: '40.673180' %>
  </div>

  <div class="field">
    <h5> <strong>Longitude:</strong> </h5>
    <%= form.label :longitude, class:"hidden" %>
    <%= form.text_field :longitude, placeholder: '73.972878' %>
  </div>

  <div class="container">
  <hr>
  </div>

  <div class="field">
    <h5> <strong>Description:</strong> </h5>
    <%= form.label :description, class:"hidden" %>
    <br>
    <%= form.text_area :description %>
  </div>

  <div class="container">
  <hr>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>
<div>
  <hr>
<%= link_to 'Back', :back, class:"btn btn-primary" %>
<br>
<br>
</div>


</div>
</div>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="card container text-center">


  <h1 class="display-4"> Listings#Index</h1>
<hr>
<br>
<h1 class="display-4"> <%#= @seller.email + "'s "%> My Listings</h1>
<hr>

<%= link_to 'Add New Listing', new_seller_listing_path(@seller), class:"btn-success btn-block btn-lg" %>

<hr>
  <% @listings.each do |listing| %>
      <div class="card">
        <br>
        <%= listing.full_street_address %>
        <br>
        <%= listing.description %>
        <br>
        <%= listing.longitude %>, <%= listing.latitude %>

        <br>
        <div>
        <%= link_to 'Show', listing %>
        <%= link_to 'Edit', edit_listing_path(listing) %>
        <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %>
        <br>
        <br>
        </div>
      </div>

  <% end %>
  <br>


<hr>
<div class="tex">
<%= link_to 'Back', :back, class:"btn btn-primary" %>
</div>
<br>

</div>

app/views/listings/new.html.erb
<div class="text-center">
  <div class="card">
  <br>
  <h1 class="display-4">New Listing</h1>

  <%= render 'form', listing: @listing %>

  <div class="container">
  <hr>
  </div>

  <div>
  <%= link_to 'Back', :back, class:"btn btn-primary" %>
  <br>
  <br>
  </div>

  </div>
</div>

app/views/listings/show.html.erb
<div class="card container">

<div class="display-4 text-center"> Listing </div>
<hr>
<div class="text-center">
<%= link_to 'Edit Listing', edit_listing_path(@listing), class:"btn btn-outline-secondary btn-sm" %>
<hr>

<p>
  <strong>Address:</strong>

  <%= @listing.full_street_address %>


<div id="map1"></div>

<script>
var lat = <%= @listing.lat %>;
var lng = <%= @listing.lng %>;

var marker;

function initMap() {
  var map = new google.maps.Map(document.getElementById('map1'), {
    zoom: 13,
    center: {lat, lng}
  });

  marker = new google.maps.Marker({
    map: map,
    draggable: true,
    animation: google.maps.Animation.DROP,
    position: {lat, lng}
  });
  marker.addListener('click', toggleBounce);
}

function toggleBounce() {
  if (marker.getAnimation() !== null) {
    marker.setAnimation(null);
  } else {
    marker.setAnimation(google.maps.Animation.BOUNCE);
  }
}

</script>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUrlQaMPYAMf2W6vaHFF7ufv-Bp6A7dZo&callback=initMap">
</script>

<br>
<hr>
<div class="text-center">
<%= link_to 'Back', :back, class:"btn btn-primary" %>
</div>
<br>

</div>