config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/test' => 'pages#test'

  get '/seller_signup' => 'sellers#new'
  post '/sellers' => 'sellers#create'

  get '/buyer_signup' => 'buyers#new'
  post '/buyers' => 'buyers#create'

  get '/login' =>   'sessions#new'
  post '/login' =>   'sessions#create_seller'
  post '/login' =>   'sessions#create_buyer'
  get '/logout' => 'sessions#destroy'

  get '/directions' => 'directions#index'

  resources :buyers

  resources :sellers do
    resources :listings, only: [:index, :new, :create]
  end
  resources :listings, only: [:show, :edit, :update, :destroy]

  get '/listings' => 'listings#all_listings'


  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'sessions#destroy'
  #
  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_secure_password
  has_many :listings, dependent: :destroy
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  def index
    @sellers = Seller.all
    # @restaurants = Restaurant.where(seller_id: @seller).paginate(page: params[:page]).order("created_at DESC")
    #### Pagination found in model.rb file(control amount of @instances per page)
  end

  def show
    @seller = Seller.find(params[:id])
    @listings = @seller.listings
    @last_listing = @listings.last
  end

  def new
  end

  def edit
    @seller = Seller.find(params[:id])
  end

  def create
    # seller = Seller.new(seller_params)
    @seller = Seller.new(seller_params)

      if @seller.save
        session[:seller_id] = @seller.id
        redirect_to current_seller

        flash[:register_success] = ["Welcome #{current_seller.email}, thank you for registering."]
      else
        flash[:register_errors] = ["REGISTER ERROR. Invalid credentials, please try again."]
        # redirect_to sellers_index_path
        redirect_to root_path
      end
  end

  def update

      @seller = Seller.find(params[:id])

      if @seller.update(seller_params)
        redirect_to @seller, :notice => "Profile updated successfully."
      else
         redirect_to @seller, :notice => ['Profile could not be updated, please try again later.']
      end
  end

  def destroy
    @seller = Seller.find(params[:id])
    if @seller.destroy
    session[:seller_id] = nil
    redirect_to root_path, :notice => 'You have deleted your profile.'
   else
     redirect_to sellers_edit_path, :notice => ["Seller can not be deleted at this time."]
   end
  end

  private

    def set_seller
      @seller = current_seller
    end

    def seller_params
      params.require(:seller).permit( :email, :password, :password_confirmation)
    end

end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<%= form_with(model: seller, local: true) do |form| %>
  <% if seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sellers/edit.html.erb
<h1>Editing Seller</h1>

<%= render 'form', seller: @seller %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', :back %>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sellers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= seller.email %></td>
        <td><%= link_to 'Show', seller %></td>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<div class="card text-center">
  <br>

  <h1 class="text-center">Seller Signup</h1>

  <div class="container">
    <hr>
  </div>


<br>

  <%= form_for :seller, url: '/sellers' do |f| %>

      <div class="form-group">
      <strong>Email:</strong>  <%= f.text_field :email, placeholder: "Enter your Email" %>
      </div>

      <div class="form-group">
        <strong>Password:</strong><%= f.password_field :password, placeholder: "Password" %>
      </div>

      <div class="form-group">
            <strong>Confirm Password:</strong>  <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
      </div>

      <br>
       <center class="submit">
        <%= f.submit "Submit", class:"btn btn-success" %>
      </center>
      <br>

      <small>
        Already have an account? <%= link_to "Click Here to Login.", login_path %>
      </small>

      <br>
  <% end %>

<br>

</div>

app/views/sellers/show.html.erb
<div class="text-center">

  <div class="card">
<br>
    <p class="display-4"> Sellers#show</p>
    <hr>
    <p class="display-4"> <%= @seller.email%>'s Listings</p>

    <div class="container">

      <hr>

      <% if current_seller = Seller.find(params[:id]) %>
        <%= link_to "Post Listing", new_seller_listing_path(@seller), class:"btn btn-success" %>
        <hr>
      <% end %>


      <% if @seller.listings.count ==  0 %>

      <h1>  <%= @seller.email.capitalize%>'s Has No Listings.</h1>

      <% else %>


      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#exampleModal">
        View All <%= @seller.email.capitalize%>'s Listings
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel"> <%= @seller.email%>'s Listings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">

              <br>
              <% @listings.each do |listing| %>

              <%= link_to "#{listing.address}", listing %>
              <br>
              <% end %>
              <br>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      <% end %>



      <hr>
      <br>

      <div id="map"></div>

      <br>

      <script>
            function initMap() {

              <% if @listings.count > 1 %>

              var lat = <%= @last_listing.lat %>;
              var lng = <%= @last_listing.lng %>;

              var zoom = 9;

              <% else %>

              var lat = 38.812016;
              var lng = -97.504928 ;

              var zoom = 4;


              <% end %>

              //
              //


              var map = new google.maps.Map(document.getElementById('map'), {
                zoom:zoom,
                center: {lat, lng}
              });

              // Create an array of alphabetical characters used to label the markers.
              var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

              // Add some markers to the map.
              // Note: The code uses the JavaScript Array.prototype.map() method to
              // create an array of markers based on a given "locations" array.
              // The map() method here has nothing to do with the Google Maps API.
              var markers = locations.map(function(location, i) {
                return new google.maps.Marker({
                  position: location,
                  label: labels[i % labels.length]
                });
              });

              // Add a marker clusterer to manage the markers.
              var markerCluster = new MarkerClusterer(map, markers,
                  {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
            }


            // <% @listings.each do |location| %>
            //
            //   var lat = <%= location.lat %>;
            //   var lng = <%= location.lng %>;
            //
            // var locations = [
            //
            //
            //   {lat, lng},
            //   {lat, lng},
            //   {lat, lng},
            //
            // ]
            //
            // <% end %>
            //

            var locations = []

            <% @listings.each do |location| %>

              var lat = <%= location.lat %>;
              var lng = <%= location.lng %>;

              locations.push({"lat":lat,"lng":lng})

            <% end %>

      </script>

      <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
      </script>

      <script async defer
      src="https://maps.googleapis.com/maps/api/js?&key=AIzaSyCb7XJAeWDd5AXTQpyjeYIU93Gc7CfUpVk&callback=initMap">
      </script>

      <div class="text-center">
      <%= link_to 'Back', :back, class:"btn btn-outline-primary" %>
      </div>
      <br>



    </div>
  </div>
</div>