config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/test' => 'pages#test'

  get '/seller_signup' => 'sellers#new'
  post '/sellers' => 'sellers#create'

  get '/buyer_signup' => 'buyers#new'
  post '/buyers' => 'buyers#create'

  get '/login' =>   'sessions#new'
  post '/login' =>   'sessions#create_seller'
  post '/login' =>   'sessions#create_buyer'
  get '/logout' => 'sessions#destroy'

  get '/directions' => 'directions#index'

  resources :buyers

  resources :sellers do
    resources :listings, only: [:index, :new, :create]
  end
  resources :listings, only: [:show, :edit, :update, :destroy]

  get '/listings' => 'listings#all_listings'


  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'sessions#destroy'
  #
  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_secure_password
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]

  def index
    @buyers = Buyer.all
  end

  def show
    @buyer = current_buyer
  end

  def new
  end

  def edit
    @buyer = Buyer.find(params[:id])
  end

  def create

    @buyer = Buyer.new(buyer_params)

      if @buyer.save
        session[:buyer_id] = @buyer.id
        redirect_to current_buyer

        flash[:register_success] = ["Welcome #{current_buyer.email}, thank you for registering."]
      else
        flash[:register_errors] = ["REGISTER ERROR. Invalid credentials, please try again."]
        # redirect_to buyers_index_path
        redirect_to root_path
      end
  end

  def update

      @buyer = Buyer.find(params[:id])

      if @buyer.update(buyer_params)
        redirect_to @buyer, :notice => "Profile updated successfully."
      else
         redirect_to @buyer, :notice => ['Profile could not be updated, please try again later.']
      end
  end

  def destroy
    @buyer = Buyer.find(params[:id])
    if @buyer.destroy
    session[:buyer_id] = nil
    redirect_to root_path, :notice => 'You have deleted your profile.'
   else
     redirect_to buyers_edit_path, :notice => ["Buyer can not be deleted at this time."]
   end
  end

  private

    def set_buyer
      @buyer = current_buyer
    end

    def buyer_params
      params.require(:buyer).permit( :email, :password, :password_confirmation)
    end

end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_form.html.erb
<%= form_with(model: buyer, local: true) do |form| %>
  <% if buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
      <% buyer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buyers/edit.html.erb
<h1>Editing Buyer</h1>

<%= render 'form', buyer: @buyer %>

<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyers_path %>

app/views/buyers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buyers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= buyer.email %></td>
        <td><%= link_to 'Show', buyer %></td>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buyer', new_buyer_path %>

app/views/buyers/new.html.erb
<div class="card text-center">
  <br>

  <h1 class="text-center">Buyer Signup</h1>

  <div class="container">
    <hr>
  </div>


<br>

  <%= form_for :buyer, url: '/buyers' do |f| %>

      <div class="form-group">
      <strong>Email:</strong>  <%= f.text_field :email, placeholder: "Enter your Email" %>
      </div>

      <div class="form-group">
        <strong>Password:</strong><%= f.password_field :password, placeholder: "Password" %>
      </div>

      <div class="form-group">
            <strong>Confirm Password:</strong>  <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
      </div>

      <br>
       <center class="submit">
        <%= f.submit "Submit", class:"btn btn-success" %>
      </center>
      <br>

      <small>
        Already have an account? <%= link_to "Click Here to Login.", login_path %>
      </small>

      <br>
  <% end %>

<br>

</div>

app/views/buyers/show.html.erb
<p id="notice"><%= notice %></p>


<%= current_buyer.email %>


<p>
  <strong>Email:</strong>
  <%= @buyer.email %>
</p>

<%= link_to 'Edit', edit_buyer_path(@buyer) %> |
<%= link_to 'Back', buyers_path %>