config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/test' => 'pages#test'

  get '/seller_signup' => 'sellers#new'
  post '/sellers' => 'sellers#create'

  get '/buyer_signup' => 'buyers#new'
  post '/buyers' => 'buyers#create'

  get '/login' =>   'sessions#new'
  post '/login' =>   'sessions#create_seller'
  post '/login' =>   'sessions#create_buyer'
  get '/logout' => 'sessions#destroy'

  get '/directions' => 'directions#index'

  resources :buyers

  resources :sellers do
    resources :listings, only: [:index, :new, :create]
  end
  resources :listings, only: [:show, :edit, :update, :destroy]

  get '/listings' => 'listings#all_listings'


  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'sessions#destroy'
  #
  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-faded">
  <a class="navbar-brand" href="/">RealEstateMapp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

    <div class="navbar-nav">

      <% if current_buyer %>

      <%= link_to "Welcome #{current_buyer.email}", buyer_path(current_buyer), class:"nav-item nav-link" %>

      <%= link_to 'Home', buyer_path(current_buyer), class:"nav-item nav-link" %>

      <%= link_to "Listings", listings_path, class:"nav-item nav-link"%>


      <li class="nav-item">
        <a class="nav-link" href="/logout"> Logout </a>
      </li>

      <% elsif current_seller %>

      <%= link_to "Welcome #{current_seller.email}", seller_path(current_seller), class:"nav-item nav-link" %>

      <%= link_to 'Home', seller_path(current_seller), class:"nav-item nav-link" %>

      <%= link_to "Listings", listings_path, class:"nav-item nav-link"%>

      <%= link_to 'Directions', directions_path, class:"nav-item nav-link" %>


      <%= link_to 'Account Settings', edit_seller_path(current_seller), class:"nav-item nav-link" %>

      <li class="nav-item">
        <a class="nav-link" href="/logout"> Logout </a>
      </li>

      <% else %>

      <%= link_to 'Home', root_url, class:"nav-item nav-link" %>

      <%= link_to "Listings", listings_path, class:"nav-item nav-link"%>


      <%= link_to 'About', about_path, class:"nav-item nav-link" %>



      <!-- <li class="nav-item">
        <%= link_to 'Buyer Login', '/buyer_login', class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to 'Buyer Signup', '/buyer_signup', class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to 'Seller Login', '/seller_login', class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to 'Seller Signup', '/seller_signup', class:"nav-link" %>
      </li> -->

      <% end %>


    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

    <title>RealEstateMapp</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">

  </head>
  <body>

    <%= render 'layouts/nav' %>

    <div class="container py-5">

      <% if current_buyer %>
        <div class="container ">
           <h4><%= link_to "Welcome #{current_buyer.email}", buyer_path(current_buyer) %> </h4>
        </div>
      <% end %>

      <% if current_seller %>
      <div class="container ">
        <h4><%= link_to "Welcome #{current_seller.email}", seller_path(current_seller) %> </h4>
      </div>
      <% end %>

      <% if notice != nil %>
        <h4 class="text-center alert-success">
        <br>
        <%= notice %>
        <br>
        <br>
      </h4>
      <% elsif alert != nil %>
        <h4 class="text-center alert-danger"><%= alert %></h4>
      <% end %>

      <%= yield %>

    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>